### ISSUE TITLE
Getting 500 after creating a new recipe - fresh installation

### ISSUE THREAD

**Issue by m-kronberg** [juriansluiman/groceri.es#12]
ERROR:app:Exception on /recipes/1/bakedsalmon [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/./views.py", line 131, in recipe
    return render_template('recipe.html', recipe=recipe)
  File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/templates/recipe.html", line 4, in top-level template code
    {% set active_page = 'recipes' %}
  File "/app/templates/layout.html", line 81, in top-level template code
    {% block content %}{% endblock %}
  File "/app/templates/recipe.html", line 14, in block 'content'
    <a class="ui teal right ribbon label" href="{{ url_for('recipes', category=recipe.category.name|slugify) }}">{{ recipe.category.name }}</a>
  File "/app/./app.py", line 48, in slug
    return slugify(value)
  File "/usr/local/lib/python3.8/site-packages/slugify/slugify.py", line 104, in slugify
    text = _unicode(text, 'utf-8', 'ignore')
TypeError: decoding to str: need a bytes-like object, Undefined found

**Comment by juriansluiman** [comment]
@m-kronberg I am a bit late to the party :blush: but could you try again with the latest code?

**Comment by juriansluiman** [comment]
Please reopen when this still occurs
