### ISSUE TITLE
Simple docker setup fails

### ISSUE THREAD

**Issue by jondoe1337** [juriansluiman/groceri.es#5]
When building the current master as a docker image like in the docs mentioned and running it like this:

`docker run -d --name groceri.es -e SECRET_KEY='mysecret' -p 84:80 groceri.es`

It fails with:

```
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
Run flask migration upgrades (show current version first)
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/cli.py", line 209, in current
    _current(directory, verbose, head_only)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 369, in current
    command.current(config, verbose=verbose, head_only=head_only)
TypeError: current() got an unexpected keyword argument 'head_only'
```

**Comment by ephygamesco** [comment]
I'm also getting this. Did you find a fix?



`Checking for script in /app/prestart.sh,
Running script /app/prestart.sh,
Run flask migration upgrades (show current version first),
Traceback (most recent call last):,
  File "/usr/local/bin/flask", line 10, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 967, in main,
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None),
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 586, in main,
    return super(FlaskGroup, self).main(*args, **kwargs),
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main,
    rv = self.invoke(ctx),
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke,
    return _process_result(sub_ctx.command.invoke(sub_ctx)),
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke,
    return _process_result(sub_ctx.command.invoke(sub_ctx)),
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke,
    return ctx.invoke(self.callback, **ctx.params),
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke,
    return callback(*args, **kwargs),
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func,
    return f(get_current_context(), *args, **kwargs),
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 426, in decorator,
    return __ctx.invoke(f, *args, **kwargs),
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke,
    return callback(*args, **kwargs),
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/cli.py", line 209, in current,
    _current(directory, verbose, head_only),
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 96, in wrapped,
    f(*args, **kwargs),
  File "/usr/local/lib/python3.6/site-packages/flask_migrate/__init__.py", line 369, in current,
    command.current(config, verbose=verbose, head_only=head_only),
TypeError: current() got an unexpected keyword argument 'head_only',`
